apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicjunkies-frontend-depl
  namespace: default
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: musicjunkies-frontend
  template: 
    metadata:
      labels:
        app: musicjunkies-frontend
    spec:
      containers:
        - name: musicjunkies-frontend
          image: vigneshbondugula/mj-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: musicjunkies-frontend-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: musicjunkies-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000